### ISSUE TITLE
Scheduling multiple triggers on same job sometimes runs out of order

### ISSUE THREAD

**Issue by vincentjames501** [FlavioF/quartz-scheduler-hazelcast-jobstore#5]
How to reproduce:

```java
@Test
  public void testScheduleOutOfOrder() throws Exception {
    JobDetail job1 = buildJob("Job1", DEFAULT_GROUP, MyJob.class);

    scheduler.scheduleJob(job1, buildTrigger("key1", DEFAULT_GROUP, job1, DateTime.now().plusMillis(2000).getMillis()));
    scheduler.scheduleJob(buildTrigger("key2", DEFAULT_GROUP, job1, DateTime.now().plusMillis(1000).getMillis()));
    scheduler.scheduleJob(buildTrigger("key3", DEFAULT_GROUP, job1, DateTime.now().plusMillis(3000).getMillis()));

    Thread.sleep(4000);
  }
```

To visualize the failure, put this in your MyJob.java

```java
    System.out.println("Processing Trigger " + jobCtx.getTrigger().getKey().getName() + " " + new Date());
```

Output is the following:

```
Processing Trigger key1 Thu Dec 03 16:54:05 CST 2015
Processing Trigger key2 Thu Dec 03 16:54:05 CST 2015
Processing Trigger key3 Thu Dec 03 16:54:06 CST 2015
```

Expected result:

```
Processing Trigger key2 Thu Dec 03 16:54:04 CST 2015
Processing Trigger key1 Thu Dec 03 16:54:05 CST 2015
Processing Trigger key3 Thu Dec 03 16:54:06 CST 2015
```

**Comment by vincentjames501** [comment]
Actually it looks like my statement isn't entirely true, it can be different jobs as well. Commenting out:

```java
props.setProperty(StdSchedulerFactory.PROP_JOB_STORE_CLASS, HazelcastJobStore.class.getName());
```

Gives the correct results. I'm assuming it has to do with locking inside the job store

**Comment by FlavioF** [comment]
Hi!

As I sayed in my readme hazelcast job store does not support order (neither FIFO or LIFO). 
Why do you need to ensure order? What is your scenario?

When you comment that line you are using the default Quartz job store (RAMJobStore) instead of Hazelcast Job Store. Normally, all the job store support order. Since Hazelcast is distributed there is no simple and efficient way to implement FIFO.

Hope it helps!
Thank you

**Comment by vincentjames501** [comment]
Our scenario is we need to schedule tasks to be performed at specific times (placing a phone call after a certain amount of time). Could you could add a hazelcast index, a comparator, and paginate to achieve the effect or ordering when finding the next trigger/job to fire? I'm neither an expert in Quartz nor Hazelcast nor have I spent much time playing with this so I'm just curious on your opinion.

**Comment by FlavioF** [comment]
Implement a way to allow ordering is possible, however it will increase a lot the complexity of the hazelcast store job.

Honestly, I didn't get why ordering is so important to you. Can you give me more information? I need to understand why this is so important in order to understand if this increase of complexity makes sense. 

Remember that a scheduled job fires at the correct time and not before. The order is only a problem when you have two jobs scheduled at same time and you want to ensure FIFO or LIFO. If you scheduled job A (at 12:01:00) and job B (at 12:02:00), the job B will be fired always after job A. The problem happens when you scheduled job A (at 12:01:00) and job B (at 12:01:00) the first fired job will be A or B (randomly).

I can't see any good reason to implement order, please let me know more. :)

Hope it helps

**Comment by vincentjames501** [comment]
Maybe I'm not explaining myself well enough. I'm not scheduling multiple jobs at the same time, I'm scheduling multiple triggers for the same job at different times and they are firing at the wrong time (and many times they are `VERY` far off from their start dates). Our goal is to effectively make a queue of scheduled triggers that trigger the same job (just with different job data an for our case a cron job won't work). If you look closely at the test in the original post I think it shows what I'm describing. One would expect trigger 2 to fire before trigger one due to the start date.

**Comment by FlavioF** [comment]
Ok! I get it now. Let me take a look into it in order to find a simple solution. Thank you for your feedback. :+1:

**Comment by FlavioF** [comment]
Please take a look into it and let me know if it is already fixed. I added your test to my test suite.

Thank you.

**Comment by FlavioF** [comment]
Sometimes the order fails due to concurrency problems (5% of the times) . 
It is related to #9.
Note that Hazelcast Job Store purpose is to work in distributed system, so even if the trigger is triggered in correct order, the job execution order isn't warranted.
